from __future__ import annotations

import importlib.util
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Annotated, Any

import typer
from rich.console import Console
from rich.table import Table

from pipespec_validator.generate import generate_with_repair
from pipespec_validator.io_utils import write_doc
from pipespec_validator.llm_runtime import LLMConfig, build_llm_config
from pipespec_validator.models import ValidationResult
from pipespec_validator.validator import validate_dict

from .coverage import build_coverage_matrix
from .eda import DataProfile, profile_data_paths, profiles_to_facts, summarize_profiles
from .question_planner import plan_questions
from .session import ElicitationSession

console = Console()


def _slug_id(value: str, fallback: str = "pipeline") -> str:
    slug = re.sub(r"[^A-Za-z0-9_-]+", "_", value.strip()).strip("_")
    if not slug:
        slug = fallback
    if not re.match(r"^[A-Za-z]", slug):
        slug = f"{fallback}_{slug}"
    return slug[:128]


def _human_name(description_text: str, source_path: Path) -> str:
    first_line = next((line.strip() for line in description_text.splitlines() if line.strip()), "")
    if first_line:
        return first_line[:80]
    return source_path.stem.replace("_", " ").replace("-", " ").title() or "Draft Pipeline"


def _format_from_path(path: str) -> str:
    suffix = Path(path).suffix.lower().lstrip(".")
    if suffix in {"jsonl", "ndjson"}:
        return "json"
    return suffix or "text"


def _deterministic_draft(
    *,
    description_text: str,
    source_path: Path,
    data_profiles: list[DataProfile],
    provider: str | None,
    model: str | None,
) -> dict[str, Any]:
    name = _human_name(description_text, source_path)
    first_profile = data_profiles[0] if data_profiles else None
    source_data_path = first_profile.path if first_profile else str(source_path)
    source_format = first_profile.format if first_profile else _format_from_path(source_data_path)
    source_connection_id = "local_filesystem"
    component_id = "extract_source_data"
    source_dataset = _slug_id(Path(source_data_path).stem or "source_data", fallback="source_data")
    timestamp = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    warnings = [
        "Deterministic baseline draft generated by pipespec elicit because no LLM draft was available.",
        "Review open elicitation questions before compiling to OPOS or generating code.",
    ]
    if first_profile and first_profile.warnings:
        warnings.extend(first_profile.warnings)

    return {
        "pipespec_version": "1.0",
        "metadata": {
            "analysis_timestamp": timestamp,
            "source_file": str(source_path),
            "llm_provider": provider or "none",
            "llm_model": model or "deterministic-baseline",
            "analysis_results": {
                "detected_patterns": ["sequential"],
                "task_executors_used": ["python"],
                "has_branching": False,
                "has_parallelism": False,
                "has_sensors": False,
                "total_components": 1,
                "complexity_score": "low",
            },
            "validation_warnings": warnings,
        },
        "pipeline_summary": {
            "name": name,
            "description": description_text.strip() or f"Draft pipeline from {source_path.name}.",
            "flow_patterns": ["sequential"],
            "task_executors": ["python"],
            "complexity": "low",
        },
        "components": [
            {
                "id": component_id,
                "name": "Extract Source Data",
                "category": "Extractor",
                "description": "Reads the profiled source data for downstream pipeline design.",
                "inputs": [source_data_path],
                "outputs": ["raw_data"],
                "executor_type": "python",
                "executor_config": None,
                "io_spec": [
                    {
                        "name": "source_data",
                        "direction": "input",
                        "kind": "file",
                        "format": source_format or "text",
                        "path_pattern": source_data_path,
                        "connection_id": source_connection_id,
                    },
                    {
                        "name": "raw_data",
                        "direction": "output",
                        "kind": "object",
                        "format": "dataframe",
                        "path_pattern": None,
                        "connection_id": None,
                    },
                ],
                "upstream_policy": {
                    "type": "none_failed",
                    "description": "Entry point component.",
                    "timeout_seconds": None,
                },
                "retry_policy": {
                    "max_attempts": 1,
                    "delay_seconds": 0,
                    "exponential_backoff": False,
                    "retry_on": [],
                },
                "concurrency": {
                    "supports_parallelism": False,
                    "supports_dynamic_mapping": False,
                    "map_over_param": None,
                    "max_parallel_instances": None,
                },
                "connections": [
                    {
                        "id": source_connection_id,
                        "type": "filesystem",
                        "purpose": "Read source data sample.",
                    }
                ],
                "datasets": {"consumes": [source_dataset], "produces": ["raw_data"]},
                "extensions": {
                    "elicitation": {
                        "draft_confidence": "low",
                        "requires_user_review": True,
                    }
                },
            }
        ],
        "flow_structure": {
            "pattern": "sequential",
            "entry_points": [component_id],
            "nodes": {
                component_id: {
                    "kind": "Task",
                    "component_type_id": component_id,
                    "upstream_policy": {"type": "none_failed", "timeout_seconds": None},
                    "next_nodes": [],
                    "branch_config": None,
                    "sensor_config": None,
                    "parallel_config": None,
                }
            },
            "edges": [],
        },
        "parameters": {
            "pipeline": {},
            "schedule": {},
            "execution": {},
            "components": {},
            "environment": {},
        },
        "integrations": {
            "connections": [
                {
                    "id": source_connection_id,
                    "name": "Local Filesystem",
                    "type": "filesystem",
                    "config": {"base_path": str(Path(source_data_path).parent)},
                    "authentication": {"type": "none"},
                    "used_by_components": [component_id],
                    "direction": "input",
                    "rate_limit": None,
                    "datasets": {"reads": [source_dataset]},
                }
            ],
            "data_lineage": {
                "sources": [source_data_path],
                "sinks": [],
                "intermediate_datasets": ["raw_data"],
            },
        },
        "extensions": {
            "elicitation": {
                "approval_state": "drafting",
                "source": "deterministic_baseline",
            }
        },
    }


def _load_parallel_extractor():
    repo_root = Path(__file__).resolve().parents[3]
    tool_path = repo_root / "tools" / "llm_extract_pipespec_parallel.py"
    if not tool_path.exists():
        return None
    spec = importlib.util.spec_from_file_location("pipespec_parallel_extractor", tool_path)
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return getattr(module, "extract_parallel", None)


def _can_use_openai_compatible(config: LLMConfig) -> bool:
    return config.provider in {
        "openai_compatible",
        "openai",
        "deepinfra",
        "deepseek",
        "openrouter",
        "ollama",
    }


def _generate_llm_draft(
    *,
    enriched_description: str,
    llm_config: LLMConfig,
    attempts: int,
    max_tokens: int,
    temperature: float,
    semantic: bool,
    draft_mode: str,
    artifacts_dir: Path | None,
    source_file: str,
) -> dict[str, Any]:
    if draft_mode == "parallel" and _can_use_openai_compatible(llm_config):
        extract_parallel = _load_parallel_extractor()
        if extract_parallel is not None:
            return extract_parallel(
                description_text=enriched_description,
                base_url=llm_config.base_url or "https://api.openai.com/v1",
                api_key=llm_config.api_key or "ollama",
                model=llm_config.model,
                max_tokens=max_tokens,
                temperature=temperature,
                segment_attempts=attempts,
                repair_attempts=attempts,
                semantic_checks=semantic,
                print_model_output=False,
                artifacts_dir=artifacts_dir,
                source_file=source_file,
            )

    return generate_with_repair(
        description_text=enriched_description,
        llm_config=llm_config,
        attempts=attempts,
        max_tokens=max_tokens,
        temperature=temperature,
        semantic_checks=semantic,
    )


def _validation_messages(result: ValidationResult) -> list[dict[str, Any]]:
    messages: list[dict[str, Any]] = []
    for item in result.errors + result.warnings:
        messages.append(
            {
                "kind": item.kind,
                "message": item.message,
                "instance_path": item.instance_path,
                "schema_path": item.schema_path,
                "details": item.details,
            }
        )
    return messages


def _enrich_description(
    *,
    description_text: str,
    eda_summary: str,
    coverage_summary: dict[str, int],
) -> str:
    return (
        f"{description_text.strip()}\n\n"
        "ELICITATION CONTEXT:\n"
        f"Coverage summary: {coverage_summary}\n\n"
        "DATA PROFILE SUMMARY:\n"
        f"{eda_summary}\n\n"
        "Generation guidance:\n"
        "- Produce a PipeSpec draft only; unresolved questions should be represented as null, empty objects, or validation_warnings.\n"
        "- Do not embed secrets or credential values.\n"
        "- Prefer explicit components for extraction, transformation, quality checks, and loading when the description supports them.\n"
    )


def _render_questions(session: ElicitationSession) -> None:
    questions = session.open_questions()
    if not questions:
        console.print("[green]No open elicitation questions.[/green]")
        return

    table = Table(title="Open Elicitation Questions", show_lines=True)
    table.add_column("Risk", style="bold")
    table.add_column("Slot")
    table.add_column("Question")
    for question in questions:
        table.add_row(question.risk, question.slot, question.question)
    console.print(table)


def run_elicit_command(
    *,
    inp: Path,
    data: list[Path],
    out: Path,
    session_out: Path | None,
    provider: str,
    model: str | None,
    api_key: str | None,
    api_key_env: str | None,
    base_url: str | None,
    attempts: int,
    max_tokens: int,
    temperature: float,
    semantic: bool,
    max_questions: int,
    draft_mode: str,
    artifacts_dir: Path | None,
) -> None:
    description_text = inp.read_text(encoding="utf-8")
    profiles = profile_data_paths(data) if data else []
    eda_summary = summarize_profiles(profiles)
    facts = profiles_to_facts(profiles)

    session = ElicitationSession(
        description_path=str(inp),
        data_paths=[str(path) for path in data],
        known_facts=facts,
        eda_profiles=[profile.to_dict() for profile in profiles],
    )

    initial_coverage = build_coverage_matrix(
        description_text=description_text,
        data_profiles=profiles,
        known_facts=facts,
        approval_state=session.approval_state,
    )
    initial_questions = plan_questions(
        initial_coverage,
        existing_questions=session.questions,
        max_questions=max_questions,
    )
    session.coverage_slots = [slot.to_dict() for slot in initial_coverage.slots]
    session.add_questions([question.to_session_question() for question in initial_questions])

    llm_config = build_llm_config(
        provider=provider,
        model=model,
        api_key=api_key,
        api_key_env=api_key_env,
        base_url=base_url,
    )
    enriched_description = _enrich_description(
        description_text=description_text,
        eda_summary=eda_summary,
        coverage_summary=initial_coverage.summary(),
    )

    draft: dict[str, Any]
    used_deterministic_fallback = False
    try:
        if draft_mode == "deterministic" or (
            not llm_config.api_key and llm_config.provider != "ollama"
        ):
            used_deterministic_fallback = True
            draft = _deterministic_draft(
                description_text=description_text,
                source_path=inp,
                data_profiles=profiles,
                provider=llm_config.provider,
                model=llm_config.model,
            )
        else:
            draft = _generate_llm_draft(
                enriched_description=enriched_description,
                llm_config=llm_config,
                attempts=attempts,
                max_tokens=max_tokens,
                temperature=temperature,
                semantic=semantic,
                draft_mode=draft_mode,
                artifacts_dir=artifacts_dir,
                source_file=str(inp),
            )
    except Exception as exc:
        used_deterministic_fallback = True
        session.metadata["llm_draft_error"] = str(exc)
        draft = _deterministic_draft(
            description_text=description_text,
            source_path=inp,
            data_profiles=profiles,
            provider=llm_config.provider,
            model=llm_config.model,
        )

    result = validate_dict(draft, semantic_checks=semantic)
    session.validation_messages = _validation_messages(result)
    session.draft_path = str(out)
    session.metadata.update(
        {
            "draft_mode": draft_mode,
            "used_deterministic_fallback": used_deterministic_fallback,
            "llm_provider": llm_config.provider,
            "llm_model": llm_config.model,
        }
    )

    final_coverage = build_coverage_matrix(
        description_text=description_text,
        data_profiles=profiles,
        draft=draft,
        validation_result=result,
        known_facts=facts,
        approval_state=session.approval_state,
    )
    follow_up_questions = plan_questions(
        final_coverage,
        existing_questions=session.questions,
        max_questions=max_questions,
    )
    session.coverage_slots = [slot.to_dict() for slot in final_coverage.slots]
    session.add_questions([question.to_session_question() for question in follow_up_questions])
    session.approval_state = "questions_pending" if session.open_questions() else "draft_ready"

    out_fmt = "yaml" if out.suffix.lower() in {".yaml", ".yml"} else "json"
    write_doc(draft, out, out_fmt)

    resolved_session_out = session_out or out.with_suffix(out.suffix + ".elicitation.json")
    session.save(resolved_session_out)

    if result.ok:
        console.print(f"[bold green]Wrote PipeSpec draft:[/bold green] {out}")
    else:
        console.print(
            f"[bold yellow]Wrote best-effort PipeSpec draft with {len(result.errors)} validation error(s):[/bold yellow] {out}"
        )
    console.print(f"[bold green]Wrote elicitation session:[/bold green] {resolved_session_out}")
    if used_deterministic_fallback:
        console.print("[yellow]Used deterministic fallback draft generation.[/yellow]")
    _render_questions(session)


def elicit_command(
    inp: Annotated[
        Path, typer.Option("--in", help="Path to a pipeline description Markdown/text file.")
    ],
    out: Annotated[
        Path, typer.Option("--out", help="Output draft PipeSpec path (.json/.yaml/.yml).")
    ],
    data: Annotated[
        list[Path] | None,
        typer.Option(
            "--data",
            help="Optional data sample path. Repeat --data for multiple files/directories.",
        ),
    ] = None,
    session_out: Annotated[
        Path | None,
        typer.Option("--session-out", help="Optional path for the elicitation session JSON."),
    ] = None,
    provider: Annotated[
        str,
        typer.Option(
            "--provider",
            help="openai|claude|deepinfra|deepseek|openrouter|ollama|openai_compatible",
        ),
    ] = "openai_compatible",
    model: Annotated[str | None, typer.Option("--model", help="Provider model id.")] = None,
    api_key: Annotated[str | None, typer.Option("--api-key", help="API key override.")] = None,
    api_key_env: Annotated[
        str | None,
        typer.Option("--api-key-env", help="Environment variable name containing the API key."),
    ] = None,
    base_url: Annotated[
        str | None,
        typer.Option("--base-url", help="Base URL for OpenAI-compatible providers."),
    ] = None,
    attempts: Annotated[int, typer.Option("--attempts", min=1, max=10)] = 3,
    max_tokens: Annotated[int, typer.Option("--max-tokens", min=256, max=16384)] = 4096,
    temperature: Annotated[float, typer.Option("--temperature", min=0.0, max=1.0)] = 0.1,
    semantic: Annotated[
        bool, typer.Option("--semantic/--no-semantic", help="Enable semantic checks.")
    ] = True,
    max_questions: Annotated[int, typer.Option("--max-questions", min=1, max=20)] = 5,
    draft_mode: Annotated[
        str,
        typer.Option(
            "--draft-mode",
            help="parallel|standard|deterministic. Parallel reuses tools/llm_extract_pipespec_parallel.py when available.",
        ),
    ] = "parallel",
    artifacts_dir: Annotated[
        Path | None,
        typer.Option("--artifacts-dir", help="Optional directory for LLM segment artifacts."),
    ] = None,
) -> None:
    if draft_mode not in {"parallel", "standard", "deterministic"}:
        raise typer.BadParameter("draft_mode must be one of: parallel, standard, deterministic")
    try:
        run_elicit_command(
            inp=inp,
            data=data or [],
            out=out,
            session_out=session_out,
            provider=provider,
            model=model,
            api_key=api_key,
            api_key_env=api_key_env,
            base_url=base_url,
            attempts=attempts,
            max_tokens=max_tokens,
            temperature=temperature,
            semantic=semantic,
            max_questions=max_questions,
            draft_mode=draft_mode,
            artifacts_dir=artifacts_dir,
        )
    except typer.Exit:
        raise
    except Exception as exc:
        console.print(f"[bold red]Elicitation failed:[/bold red] {exc}")
        raise typer.Exit(code=2) from exc
